# Vector Arithmetic

In [14]:
import numpy as np

In [15]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

## Vector Addition / Subtraction

In [16]:
a+b

array([30, 60, 90])

Dimensional mismatches cause errors:

In [17]:
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [12]:
a-b

array([10, 20, 30])

## Vector Multiplication / Division

In [18]:
a*b

array([ 200,  800, 1800])

In [20]:
a/b

array([2., 2., 2.])