# Vector Arithmetic

In [35]:
import numpy as np

In [36]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

## Vector Addition / Subtraction

In [37]:
a+b

array([30, 60, 90])

Dimensional mismatches cause errors:

In [38]:
# a+c

In [39]:
a-b

array([10, 20, 30])

## Vector Multiplication / Division

In [40]:
a*b

array([ 200,  800, 1800])

In [41]:
a/b

array([2., 2., 2.])

## np.arrays are distinct from regular arrays in Python:

In [42]:
# For a given scalar
scalar=2

In [43]:
# With a python list
list_a = [10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [44]:
# And the same list as a np.array
list_as_array = np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]


### Multiplying the python list multiplies the amount of elements

In [45]:
scalar * list_a

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

### Multiplying the np.array by a scalar mutliplies each value by the scalar.

In [46]:
scalar * list_as_array

array([20, 22, 24, 26, 28, 30])